export const initialRewards = [
    {
        id: 1,
        type: "Cupom",
        name: "5% OFF na Loja FURIA",
        description: "Desconto válido para qualquer item no site oficial.",
        coupon: "FURIA5",
        cost: 100,
        unlocked: false,
    },
    {
        id: 2,
        type: "Cupom",
        name: "10% OFF na Loja FURIA",
        description: "Desconto válido para qualquer item no site oficial.",
        coupon: "FURIA10",
        cost: 200,
        unlocked: false,
    },
    {
        id: 3,
        type: "Cupom",
        name: "15% OFF na Loja FURIA",
        description: "Desconto válido para qualquer item no site oficial.",
        coupon: "FURIA15",
        cost: 300,
        unlocked: false,
    },
    {
        id: 4,
        type: "Cupom",
        name: "20% OFF na Loja FURIA",
        description: "Desconto válido para qualquer item no site oficial.",
        coupon: "FURIA20",
        cost: 400,
        unlocked: false,
    },
    {
        id: 5,
        type: "Cupom",
        name: "25% OFF na Loja FURIA",
        description: "Desconto válido para qualquer item no site oficial.",
        coupon: "FURIA25",
        cost: 500,
        unlocked: false,
    },
    {
        id: 6,
        type: "Cupom",
        name: "30% OFF na Loja FURIA",
        description: "Desconto válido para qualquer item no site oficial.",
        coupon: "FURIA30",
        cost: 600,
        unlocked: false,
    },
    {
        id: 7,
        type: "Wallpaper",
        name: "Wallpaper Oficial - CS:GO",
        description: "Baixe o wallpaper exclusivo da FURIA para o CS",
        src: "CS",
        cost: 50,
        unlocked: false,
    },
    {
        id: 8,
        type: "Wallpaper",
        name: "Wallpaper Oficial - LOL",
        description: "Baixe o wallpaper exclusivo da FURIA para o LOL",
        src: "LOL",
        cost: 50,
        unlocked: false,
    },
    {
        id: 9,
        type: "Wallpaper",
        name: "Wallpaper Oficial - Valorant",
        description: "Baixe o wallpaper exclusivo da FURIA para o Valorant",
        src: "Val",
        cost: 50,
        unlocked: false,
    },
    {
        id: 10,
        type: "Wallpaper",
        name: "Wallpaper Oficial - Rainbow Six Siege",
        description: "Baixe o wallpaper exclusivo da FURIA para o R6",
        src: "R6",
        cost: 50,
        unlocked: false,
    },
];